name: Testing

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup override set ${{ matrix.toolchain }}
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt
      - name: Display toolchain
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint on stable toolchain
        if: ${{ matrix.toolchain == 'stable' }}
        run: |
          cargo clippy --all-features --message-format=json | clippy-sarif | tee clippy-results.sarif | sarif-fmt
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true
      - name: Test on stable toolchain
        if: ${{ matrix.toolchain == 'stable' }}
        run: |
          cargo test --workspace